# Choose a Base image that contains python
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install -r requirements.txt

# Run the Python script
CMD ["python", "Habyt_test_ETL.py"]
